# Dev values for ingestion.
nameOverride: ingestion
exports:
  data:
    replicaCount: 1
    image:
      pullPolicy: Always
    telemetry:
      level: "info"
    reason: "new dev deploy"
    current: true
    resources:
      requests:
        cpu: 110m
        memory: 512Mi
      limits:
        cpu: 194m
        memory: 512Mi
