apiVersion: v2
name: ingestion
version: v0.1.0
appVersion: v0.1.0
description: Fabrikam Drone Ingestion Service
type: application
home: https://learn.microsoft.com/azure/architecture/reference-architectures/containers/aks-microservices/aks-microservices
sources:
  - https://github.com/mspnp/fabrikam-dronedelivery-workload
dependencies:
- name: ingestion-dev
  repository: "file://envs/ingestion-dev"
  version: v0.1.0
  condition: envs.dev
  import-values:
    - data

- name: ingestion-prod
  repository: "file://envs/ingestion-prod"
  version: v0.1.0
  condition: envs.prod
  import-values:
    - data

- name: ingestion-qa
  repository: "file://envs/ingestion-qa"
  version: v0.1.0
  condition: envs.qa
  import-values:
    - data

- name: ingestion-staging
  repository: "file://envs/ingestion-staging"
  version: v0.1.0
  condition: envs.staging
  import-values:
    - data
maintainers:
  - email: v-fean@microsoft.com
    name: ferantivero
